# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('team_leader', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('vk', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('date', models.DateField()),
                ('sent_date', models.DateField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Quest')),
            ],
        ),
    ]
